// src/pages/Setup.tsx
import { createSignal } from "solid-js";
import { useApiClient } from "~/context/ApiClient";
import { PostSystemSetupBody } from "~/lib/api/types";

const Setup = () => {
  const apiClient = useApiClient();

  const [page, setPage] = createSignal(0);

  let userForm!: HTMLFormElement;

  function nextPage() {
    setPage((prev) => prev + 1);
  }

  function prevPage() {
    setPage((prev) => prev - 1);
  }

  function finishSetup() {
    const userFormData = Object.fromEntries(new FormData(userForm));
    const body = PostSystemSetupBody.parse(userFormData);
    apiClient
      .setup(body)
      .then(() => (window.location.href = "/"))
      .catch((e) => console.error(e));
  }

  return (
    <>
      <div class={`${page() === 0 ? "" : "hidden"}`}>
        <p>Page 1: User Creation</p>
        <form
          ref={userForm}
          class="flex flex-col gap-2"
          onSubmit={(e) => {
            e.preventDefault();
          }}
        >
          <label for="username">Username</label>
          <input id="username" name="username" type="text" />

          <label for="new-password">Password</label>
          <input
            id="new-password"
            name="password"
            type="password"
            autocomplete="new-password"
          />

          <label for="passwordConfirm">Confirm Password</label>
          <input
            id="passwordConfirm"
            name="passwordConfirm"
            type="password"
            autocomplete="new-password"
          />
        </form>
        <button onClick={nextPage}>Next Page</button>
      </div>

      <div class={`${page() === 1 ? "" : "hidden"}`}>
        <p>Page 2: Summary</p>
        <button onClick={prevPage}>Prev Page</button>
        <button onClick={finishSetup}>Finish Setup</button>
      </div>
    </>
  );
};

export default Setup;

// src/routes/(setup)/setup/+page.svelte
<script lang="ts">
  type Page = "user-creation" | "finish";
  let page: Page = "user-creation";

  function nextPage() {
    switch (page) {
      case "user-creation":
        page = "finish";
    }
  }
</script>

<form class="flex flex-col gap-6" method="POST">
  {#if page === "user-creation"}
    <div class="flex flex-col">
      <div class="flex flex-col gap-1">
        <label class="text-sm uppercase tracking-wide" for="username">
          Username
        </label>
        <input
          class="border-1 h-12 rounded-[50px] border-[--input-border-color] bg-[--input-bg-color] px-5 text-[--input-fg-color] placeholder:text-[--input-placeholder-color] focus:border-[--input-focus-border-color] focus:ring-0"
          id="username"
          name="username"
          type="text"
          placeholder="Username"
        />
      </div>
      <div class="flex flex-col gap-1">
        <label class="text-sm uppercase tracking-wide" for="password">
          Password
        </label>
        <input
          class="border-1 h-12 rounded-[50px] border-[--input-border-color] bg-[--input-bg-color] px-5 text-[--input-fg-color] placeholder:text-[--input-placeholder-color] focus:border-[--input-focus-border-color] focus:ring-0"
          id="password"
          name="password"
          type="text"
          placeholder="Password"
        />
      </div>

      <button
        class="button-primary w-fit rounded px-4 py-2"
        type="button"
        onclick={() => {
          page = "finish";
        }}>Next Page</button
      >
    </div>
  {/if}

  {#if page === "finish"}
    <div class="flex flex-col">
      <p class="text-xl">Setup Summary</p>
    </div>
  {/if}
</form>
