// src/lib/components/AudioPlayer.tsx
import { createAudio } from "@solid-primitives/audio";
import { BiRegularSkipNext, BiRegularSkipPrevious } from "solid-icons/bi";
import { HiSolidChevronDown, HiSolidPause, HiSolidPlay } from "solid-icons/hi";
import {
  Match,
  Switch,
  createEffect,
  createSignal,
  onCleanup,
  onMount,
} from "solid-js";
import { useMusicManager } from "~/context/MusicManager";
import LoadingSpinner from "~/lib/components/LoadingSpinner";
import Slider from "~/lib/components/Slider";
import { formatTime } from "~/lib/utils";

function getVolume() {
  const vol = localStorage.getItem("player-volume");
  if (vol) {
    return parseFloat(vol);
  }

  return 1.0;
}

function getMuted() {
  const muted = localStorage.getItem("player-muted");
  return muted == "true";
}

const AudioPlayer = () => {
  const [trackSource, setTrackSource] = createSignal("");
  const [trackName, setTrackName] = createSignal("");
  const [artistName, setArtistName] = createSignal("");
  const [coverArtUrl, setCoverArtUrl] = createSignal("");
  const [updatedServer, setUpdatedServer] = createSignal(false);

  const [volume, setVolume] = createSignal(getVolume());
  const [muted, setMuted] = createSignal(getMuted());
  const [audio, controls] = createAudio(trackSource, undefined, volume);

  const [showPlayQueue, setShowPlayQueue] = createSignal(false);

  const musicManager = useMusicManager();

  function ended() {
    console.log("Ended");

    if (!musicManager.isEndOfQueue()) {
      musicManager.nextTrack();
      controls.play();
    }
  }

  onMount(() => {
    audio.player.addEventListener("ended", ended);
    musicManager.emitter.on("onQueueUpdated", () => {
      const track = musicManager.getCurrentTrack();
      if (track) {
        setTrackName(track.name);
        setTrackSource(track.source);
        setArtistName(track.artistName);
        setCoverArtUrl(track.coverArt);
      } else {
        setTrackName("");
        setTrackSource("");
        setArtistName("");
        setCoverArtUrl("");

        audio.player.removeAttribute("src");
        audio.player.load();
      }
      // controls.seek(0);
      setTimeout(() => {
        setUpdatedServer(false);
      }, 200);
    });

    musicManager.emitter.on("requestPlay", () => {
      controls.play();
    });

    musicManager.emitter.on("requestPause", () => {
      controls.pause();
    });

    musicManager.emitter.on("requestPlayPause", () => {
      if (audio.state == "playing") controls.pause();
      else if (audio.state == "paused") controls.play();
    });

    onCleanup(() => {
      audio.player.removeEventListener("ended", ended);
    });
  });

  createEffect(() => {
    if (!updatedServer() && audio.currentTime >= audio.duration * 0.3) {
      musicManager.markAsListened();
      setUpdatedServer(true);
    }
  });

  createEffect(() => {
    if (muted()) {
      controls.setVolume(0);
    } else {
      const vol = getVolume();
      controls.setVolume(vol);
    }
  });

  const [open, setOpen] = createSignal(false);

  return (
    <>
      <div
        class="fixed bottom-0 left-0 right-0 z-30 h-16 bg-purple-600"
        classList={{
          hidden: open(),
        }}
        onClick={() => {
          setOpen(true);
        }}
      >
        <div class="flex">
          <img
            class="aspect-square w-12 object-cover"
            src={coverArtUrl()}
            alt="Cover Art"
          />
          <div class="flex flex-col">
            <p>{trackName()}</p>
            <p>{artistName()}</p>
          </div>
        </div>
      </div>
      <div
        class={`fixed left-0 right-0 top-0 h-screen bg-purple-400 transition-transform duration-300 ${open() ? "" : "translate-y-[100%]"}`}
      >
        <div class="relative flex flex-col items-center justify-center">
          <button
            class="absolute left-4 top-4 rounded-full p-2 hover:bg-black/70"
            onClick={() => setOpen(false)}
          >
            <HiSolidChevronDown class="h-10 w-10" />
          </button>
          <img
            class="aspect-square w-80 rounded object-cover"
            src={coverArtUrl()}
            alt="Track Cover Art"
          />
          <p class="text-lg font-medium">{trackName()}</p>
          <p class="">{artistName()}</p>
          <div class="flex items-center gap-4">
            <button
              onClick={() => {
                musicManager.prevTrack();
                controls.play();
              }}
            >
              <BiRegularSkipPrevious class="h-12 w-12" />
            </button>

            <Switch
              fallback={
                <>
                  <button
                    class="rounded-full bg-white p-3"
                    onClick={() => controls.play()}
                  >
                    <HiSolidPlay class="h-12 w-12" />
                  </button>
                </>
              }
            >
              <Match when={audio.state == "playing"}>
                <button
                  class="rounded-full bg-white p-3"
                  onClick={() => controls.pause()}
                >
                  <HiSolidPause class="h-12 w-12" />
                </button>
              </Match>
              <Match when={audio.state == "paused" || audio.state == "ready"}>
                <button
                  class="rounded-full bg-white p-3"
                  onClick={() => controls.play()}
                >
                  <HiSolidPlay class="h-12 w-12" />
                </button>
              </Match>
              <Match when={audio.state == "loading"}>
                <LoadingSpinner />
              </Match>
            </Switch>

            <button
              onClick={() => {
                musicManager.nextTrack();
                controls.play();
              }}
            >
              <BiRegularSkipNext class="h-12 w-12" />
            </button>
          </div>

          <div class="relative h-4 w-full">
            <Slider
              initialValue={0}
              value={audio.currentTime / audio.duration}
              onUpdate={(p) => {
                controls.seek(p * audio.duration);
              }}
            />
          </div>

          <p>
            {formatTime(audio.currentTime)} /{" "}
            {formatTime(Number.isNaN(audio.duration) ? 0 : audio.duration)}
          </p>
        </div>
      </div>
    </>
    // <div class="relative h-full">
    //   <Slider
    //     initialValue={0}
    //     value={audio.currentTime / audio.duration}
    //     onUpdate={(p) => {
    //       controls.seek(p * audio.duration);
    //     }}
    //   />

    //   <div class="grid h-full grid-cols-footer">
    //     <div class="flex items-center bg-cyan-600">
    //       <div class="flex items-center">
    //         <button
    //           onClick={() => {
    //             musicManager.prevTrack();
    //             controls.play();
    //           }}
    //         >
    //           <BiRegularSkipPrevious size={48} />
    //         </button>

    //         <Switch
    //           fallback={
    //             <>
    //               <button onClick={() => controls.play()}>
    //                 <HiSolidPlay size={48} />
    //               </button>
    //             </>
    //           }
    //         >
    //           <Match when={audio.state == "playing"}>
    //             <button onClick={() => controls.pause()}>
    //               <HiSolidPause size={48} />
    //             </button>
    //           </Match>
    //           <Match when={audio.state == "paused" || audio.state == "ready"}>
    //             <button onClick={() => controls.play()}>
    //               <HiSolidPlay size={48} />
    //             </button>
    //           </Match>
    //           <Match when={audio.state == "loading"}>
    //             <LoadingSpinner />
    //           </Match>
    //         </Switch>
    //         <button
    //           onClick={() => {
    //             musicManager.nextTrack();
    //             controls.play();
    //           }}
    //         >
    //           <BiRegularSkipNext size={48} />
    //         </button>
    //       </div>

    //       <p class="hidden min-w-20 text-xs font-medium lg:block">
    //         {formatTime(audio.currentTime)} /{" "}
    //         {formatTime(Number.isNaN(audio.duration) ? 0 : audio.duration)}
    //       </p>
    //     </div>

    //     <div class="flex items-center justify-center gap-2 bg-amber-600 align-middle">
    //       <img
    //         class="aspect-square h-12 rounded object-cover"
    //         src={coverArtUrl()}
    //         alt="Cover Art"
    //       />
    //       <div class="flex flex-col">
    //         <p class="line-clamp-1 text-ellipsis" title={trackName()}>
    //           {trackName()}
    //         </p>

    //         <p class="line-clamp-1 min-w-80 text-ellipsis text-sm text-gray-800">
    //           {artistName()}
    //         </p>
    //       </div>
    //     </div>
    //     <div class="flex items-center justify-evenly bg-violet-500">
    //       <div class="relative flex w-24 translate-y-1.5 items-center">
    //         <Slider
    //           initialValue={getVolume()}
    //           onUpdate={(p) => {
    //             if (!muted()) {
    //               setVolume(p);
    //             }
    //             localStorage.setItem("player-volume", p.toString());
    //           }}
    //         />
    //       </div>
    //       <button
    //         onClick={() => {
    //           const res = setMuted((prev) => !prev);
    //           localStorage.setItem("player-muted", res.toString());
    //         }}
    //       >
    //         <Switch>
    //           <Match when={!muted()}>
    //             <HiSolidSpeakerWave size={24} />
    //           </Match>
    //           <Match when={muted()}>
    //             <HiSolidSpeakerXMark size={24} />
    //           </Match>
    //         </Switch>
    //       </button>
    //       <button onClick={() => setShowPlayQueue(true)}>
    //         <HiSolidQueueList size={24} />
    //       </button>
    //     </div>
    //   </div>

    //   <PlayQueue
    //     isOpen={showPlayQueue()}
    //     close={() => setShowPlayQueue(false)}
    //   />
    // </div>
  );
};

export default AudioPlayer;

// src/lib/components/AudioPlayer.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { musicManager } from "$lib/music-manager";
  import LargePlayer from "$lib/components/audio/LargePlayer.svelte";
  import SmallPlayer from "$lib/components/audio/SmallPlayer.svelte";

  let showPlayer = $state(false);

  let loading = $state(false);
  let playing = $state(false);
  let currentTime = $state(0);
  let duration = $state(0);
  let volume = $state(0);

  let trackName = $state("");
  let artistName = $state("");
  let coverArt = $state("");

  let muted = $state(false);

  let audio: HTMLAudioElement;

  function getVolume(): number {
    const volume = localStorage.getItem("player-volume");
    if (volume) {
      return parseFloat(volume);
    }

    return 1.0;
  }

  function getMuted(): boolean {
    const muted = localStorage.getItem("player-muted");
    if (muted) {
      return muted === "true";
    }

    return false;
  }

  onMount(() => {
    audio = new Audio();

    audio.addEventListener("canplay", () => {
      console.log("canplay");
      loading = false;
    });

    audio.addEventListener("loadstart", () => {
      console.log("loadstart");
      loading = true;
    });

    audio.addEventListener("loadedmetadata", () => {
      console.log("loadedmetadata");
      currentTime = audio.currentTime;
      duration = audio.duration;
    });

    audio.addEventListener("progress", () => {
      console.log("progress");
    });

    audio.addEventListener("timeupdate", () => {
      currentTime = audio.currentTime;
    });

    audio.addEventListener("loadeddata", () => {
      console.log("loadeddata");
    });

    audio.addEventListener("playing", () => {
      console.log("playing");
      playing = true;
    });

    audio.addEventListener("pause", () => {
      console.log("pause");
      playing = false;
    });

    audio.addEventListener("load", () => {
      console.log("load");
    });

    audio.addEventListener("ended", () => {
      musicManager.nextTrack();
      musicManager.requestPlay();
    });

    musicManager.emitter.on("onTrackChanged", () => {
      const track = musicManager.getCurrentTrack();
      console.log(track);
      if (track) {
        trackName = track.name;
        artistName = track.artistName;
        coverArt = track.coverArt;

        audio.src = track.source;
      } else {
        trackName = "";
        artistName = "";
        coverArt = "";

        audio.removeAttribute("src");
        audio.load();
      }
    });

    musicManager.emitter.on("requestPlay", () => {
      audio.play();
    });

    musicManager.emitter.on("requestPause", () => {
      audio.pause();
    });

    musicManager.emitter.on("requestPlayPause", () => {
      if (playing) {
        audio.pause();
      } else {
        audio.play();
      }
    });
  });

  onMount(() => {
    volume = getVolume();
    muted = getMuted();

    if (muted) {
      audio.volume = 0.0;
    } else {
      audio.volume = volume;
    }
  });

  onMount(() => {
    let unsub = musicManager.emitter.on("onQueueUpdated", () => {
      showPlayer = !musicManager.isQueueEmpty();
    });

    return () => {
      unsub();
    };
  });

  $effect(() => {
    if (showPlayer) {
      document.body.setAttribute("data-player", "true");
    } else {
      document.body.setAttribute("data-player", "false");
    }
  });
</script>

<LargePlayer
  {showPlayer}
  {playing}
  {loading}
  {trackName}
  {artistName}
  {coverArt}
  {currentTime}
  {duration}
  {volume}
  audioMuted={muted}
  onPlay={() => {
    audio.play();
  }}
  onPause={() => {
    audio.pause();
  }}
  onNextTrack={() => {
    musicManager.nextTrack();
    audio.play();
  }}
  onPrevTrack={() => {
    musicManager.prevTrack();
    audio.play();
  }}
  onSeek={(e) => {
    audio.currentTime = e;
  }}
  onVolumeChanged={(e) => {
    if (!muted) {
      audio.volume = e;
    }

    volume = e;
    localStorage.setItem("player-volume", e.toString());
  }}
  onToggleMuted={() => {
    muted = !muted;
    localStorage.setItem("player-muted", muted ? "true" : "false");

    if (muted) {
      audio.volume = 0;
    } else {
      audio.volume = volume;
    }
  }}
/>

<SmallPlayer
  {showPlayer}
  {playing}
  {loading}
  {trackName}
  {artistName}
  {coverArt}
  {currentTime}
  {duration}
  {volume}
  audioMuted={false}
  onPlay={() => {
    audio.play();
  }}
  onPause={() => {
    audio.pause();
  }}
  onNextTrack={() => {
    musicManager.nextTrack();
    audio.play();
  }}
  onPrevTrack={() => {
    musicManager.prevTrack();
    audio.play();
  }}
  onSeek={(e) => {
    audio.currentTime = e;
  }}
  onVolumeChanged={(e) => {
    if (!muted) {
      audio.volume = e;
    }

    volume = e;
    localStorage.setItem("player-volume", e.toString());
  }}
  onToggleMuted={() => {
    muted = !muted;
    localStorage.setItem("player-muted", muted ? "true" : "false");

    if (muted) {
      audio.volume = 0;
    } else {
      audio.volume = volume;
    }
  }}
/>

<!-- <div
  class="fixed bottom-0 left-0 right-0 flex h-14 items-center gap-4 bg-red-300 px-2"
>
  <div class="flex gap-2">
    <button
      onclick={() => {
        musicManager.prevTrack();
        musicManager.requestPlay();
      }}>Prev</button
    >

    {#if loading}
      <p>Loading...</p>
    {:else if playing}
      <button
        onclick={() => {
          musicManager.requestPause();
        }}>Pause</button
      >
    {:else}
      <button
        onclick={() => {
          musicManager.requestPlay();
        }}>Play</button
      >
    {/if}

    <button
      onclick={() => {
        musicManager.nextTrack();
        musicManager.requestPlay();
      }}>Next</button
    >
  </div>

  <div class="flex flex-col">
    <p class="text-sm">{trackName}</p>
    <p class="text-xs">{artistName}</p>
  </div>

  <p>{formatTime(currentTime)} / {formatTime(duration)}</p>
</div> -->
